on:
  push:
    branches: [main]

name: Stackfolio gcloud Function Starter | Production - Cloud Functions CI/CD
env:
  SERVICE: stackfolio-gcloud-function-prod
  REGION: australia-southeast1 # Change this to your preferred region
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  NODE_ENV: production # Set the environment to production
  # Add more environment variables as needed

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Write secrets into env
        run: |
          touch .env.yaml
          echo 'NODE_ENV: ${{ env.NODE_ENV }}' >> .env.yaml
          cat .env.yaml

      - name: Deploy
        run: |-
          gcloud functions deploy ${{ env.SERVICE }} \
          --entry-point 'index' \
          --env-vars-file .env.yaml \
          --runtime nodejs20 \
          --allow-unauthenticated \
          --region ${{ env.REGION }} \
          --memory 256MB \
          --trigger-http
